Añadir título del proyecto en la memoria
jero-dev/proyecto-tfg pull request #11
Opened 2023-03-06 19:29 UTC by jero-dev

El contenido de esta solicitud de cambios es solamente la adición del título a la documentación.

Cuando se fusione esta solicitud de cambios, se resolverán las peticiones:

#12 Cambiar el título y el subtitulo de la documentación 

Y se añadirá valor a la historia de usuario:

#2 [HU00]

2023-03-06 19:52 UTC, JJ requested changes
Recuerda que el título tiene que ser el mismo que en Swad... En tu caso es

"Gestión de ofertas publicadas en canales de Discord y Telegram"

Luego puedes poner en el resumen y subtítulos lo que quieras, pero el título no puede variar porque lo ha aprobado la comisión.

2023-03-06 19:52 UTC, JJ commented on doc/portada/portada.tex
> +{\Huge\bfseries Resumidor de ofertas provenientes de canales \\}
¿Resumidor existe?

2023-03-06 19:52 UTC, JJ commented on doc/portada/portada.tex
> +{\large\bfseries Herramienta como ayuda para el seguimiento de precios para productos }
¿No quedaría mejor quitando "como ayuda"?

2023-03-06 20:08 UTC, jero-dev commented on doc/portada/portada.tex
> +{\Huge\bfseries Resumidor de ofertas provenientes de canales \\}
He buscado, y efectivamente no existe. De todas maneras haré el cambio de título por el que aparece en SWAD 🙂

2023-03-06 20:08 UTC, jero-dev commented on doc/portada/portada.tex
> +{\large\bfseries Herramienta como ayuda para el seguimiento de precios para productos }
Estoy de acuerdo. Lo quito ahora mismo.

2023-03-07 06:42 UTC, JJ requested changes
Mejor que revises la traducción a inglés; por otro lado recuerda que todo PR tiene que ir asociado a un issue y este a un HU. En este caso específico, puede ir asociado directamente a un HU: #2

2023-03-07 06:42 UTC, JJ commented on .github/workflows/documentation-ci.yml
> +    branches:
¿Por qué querrías hacer un PR a otra rama y por qué no querrías lanzar este workflow?

2023-03-07 06:42 UTC, JJ commented on doc/prefacios/prefacio.tex
> +{\large\bfseries Gestión de ofertas publicadas en canales de Discord y Telegram \\ Herramienta para el seguimiento de precios para productos }\\
¿No sería mejor cualificar "productos"?

2023-03-07 20:37 UTC, jero-dev commented on doc/prefacios/prefacio.tex
> +{\large\bfseries Gestión de ofertas publicadas en canales de Discord y Telegram \\ Herramienta para el seguimiento de precios para productos }\\
Con cualificar, ¿a qué te refieres? ¿Realizar el cambio como "Herramienta para cualificar el precio de productos"? ¿O como "Herramienta para cualificar productos"?

2023-03-08 06:33 UTC, JJ commented on doc/prefacios/prefacio.tex
> +{\large\bfseries Gestión de ofertas publicadas en canales de Discord y Telegram \\ Herramienta para el seguimiento de precios para productos }\\
Qué tipo de productos se publicitan ahí, más que nada

2023-03-11 11:39 UTC, jero-dev commented on doc/prefacios/prefacio.tex
> +{\large\bfseries Gestión de ofertas publicadas en canales de Discord y Telegram \\ Herramienta para el seguimiento de precios para productos }\\
¡Ah! Ahora lo entendí mejor 😅 Subo los cambios.

2023-03-15 06:48 UTC, JJ approved these changes
En general, como te dije, los PRs tienen que estar asociados a un issue, que a su vez esté asociado a una historia de usuario. En este caso el problema que se resuelve (la memoria no tiene título) posiblemente no necesite un issue aparte, pero *si* necesita una HU. Por favor, hazlo así (en el cuerpo del PR) antes de mergearlo.

2023-03-17 08:21 UTC, merged