Añadir la definición de problema y solución
jero-dev/proyecto-tfg pull request #13
Opened 2023-03-21 21:36 UTC by jero-dev

En esta solicitud de cambios se incluye el contenido de la introducción para definir el problema y la solución del proyecto.

En cuanto se fusione esta solicitud de cambios, se cerrarán las peticiones:

- #5

Y se añadirá más valor a las peticiones:

- #2

2023-03-22 06:10 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Este proyecto es software libre, y está liberado con la licencia GPL 3\cite{gplv3}.\\
Es v3, pero aparte no sé si merece la pena crear una cita para eso. Se puede simplemente enlazar, y mejor si es en el mismo repo.

2023-03-22 06:20 UTC, JJ requested changes
¿Has mirado los documentos que pasé por el grupo de Telegram? Ahí aclaro cómo va el proceso desde el examen de una situación hasta el planteamiento de una serie de objetivos, pasando por historias de usuario e hitos. Por favor, repásalos y plantea de nuevo lo que has escrito.

2023-03-22 06:20 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\textbf{Tener un seguimiento del precio de un producto en las principales tiendas online.}\\
No es un problema, es una solución. ¿Por qué quiere tener alguien un seguimiento del precio de un producto? ¿Quiere ahorrarse dinero? ¿Tiene un presupuesto limitado?
La ingeniería del software es resolver problemas, y es imprescindible tener claro el problema desde el principio para poder aportar una solución adecuada y poder responder a todas las preguntas que se planteen.
En tu caso específico, yo trataría de bajar un poco el nivel del problema; no dirigirlo a usuarios finales, sino a creadores de herramientas.  Es decir, el problema sería tener una referencia centralizada de ofertas dispersas, y poder identificar claramente de qué productos se trata. Recuerda que los retos principales van a estar en el procesamiento de los mensajes de diferentes plataformas.
Eventualmente esa persona o incluso tú mismo podrás construir una herramienta (que habrá que ver qué herramienta es, por otro lado) que permita tener el seguimiento del precio, o avisar de alguna otra cosa. Pero poner desde el principio esto como problema excluye otros (avisar cuando cualquier producto esté por debajo de un precio) y por otro lado, tampoco aclara demasiado qué es lo que se quiere (¿qué es exactamente un *seguimiento*?)
Si pones desde el principio el problema y quién lo tiene (una persona tiene 20€ al mes y le gustan los juegos de no sé qué categoría; una persona quiere vender sus juegos de segunda mano en Wallapop y quiere saber cuánto valen los juegos de alguna categoría; una persona quiere crear una herramienta para los que venden en Wallapop) es mucho más fácil iniciar la modelización y código del problema.

2023-03-22 06:20 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Es por eso que se ha decidido tener una solución basada en resumir este tipo de ofertas para el usuario cuando este busque por un videojuego en concreto,
"Resumir" no es "hacer un seguimiento". Por eso hay que aclarar el problema, porque puedes interpretar esa solución de muchas formas diferentes.

2023-03-25 13:32 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +Este proyecto es software libre, y está liberado con la licencia GPL 3\cite{gplv3}.\\
Añadida la licencia en el repositorio y referenciada mediante enlace en la documentación.

2023-03-25 13:34 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +\textbf{Tener un seguimiento del precio de un producto en las principales tiendas online.}\\
Sí, es cierto. Estuve revisando la documentación y no llegué a poner el problema en cuestión. Lo he cambiado por el problema que pensé desde el principio.

2023-03-25 13:36 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +Es por eso que se ha decidido tener una solución basada en resumir este tipo de ofertas para el usuario cuando este busque por un videojuego en concreto,
He cambiado la solución por una más exacta y que sigue la idea de "Resumir".

2023-03-27 05:56 UTC, JJ commented
> En esta solicitud de cambios se incluye el contenido de la introducción para definir el problema y la solución del proyecto.
> 
> En cuanto se fusione esta solicitud de cambios, se cerrarán las peticiones:

A menos que lo hayas puesto en un commit, tienes que poner explícitamente `closes` delante del número de issue para que se cierre al fusionar el PR.

2023-03-27 06:05 UTC, JJ requested changes
El principal problema es que hay que plantear los problemas, y de ellos los objetivos, con mucha claridad, porque es la base sólida sobre la que hay que construir el proyecto.

2023-03-27 06:05 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +pero que puede llegar a ser bastante difícil encontrar la última oferta del producto que queramos adquirir por cada una de ellas
Aquí apuntas al problema, pero no lo expresas con claridad. Es esencial en el principio de la memoria (y del proyecto) plantear el problema o problemas que se van a abordar con claridad.
Aquí puedes también incluir que no hay una forma sin ambigüedad de referirse a un juego, por ejemplo

2023-04-11 17:37 UTC, jero-dev commented
He llegado a reescribir el contenido de la introducción, añadiendo más citas y explicando un poco más el contexto.

2023-04-12 06:02 UTC, JJ requested changes
Échale un vistazo a la formulación de objetivos y reescríbelos, por favor. Lo que has puesto tiene el problema de ser demasiado concreto por un lado ("un texto") y por otro lado demasiado impreciso ("las últimas" ¿de cuando? "cada" videojuego ¿de todos los que existan?)
Recuerda que hay dos focos principales: 
1. Construir clientes de Discord y Telegram que sean capaces de recibir esas ofertas
2. Entender la información semiestructurada que se publica en esos canales.
El objetivo final del proyecto puede ser lo que comentas; pero lo que tendrías que poner en la memoria son los objetivos parciales, que son los que presentan verdaderos retos.

2023-04-12 18:08 UTC, jero-dev commented on doc/bibliografia.bib
> +	howpublished = {\url{https://discord.com/}}
Cierto. Los he cambiado por pies de página.

2023-04-12 18:11 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +    \textbf{Resumir en un solo texto las últimas ofertas de cada tienda por cada videojuego.}
He dejado varios objetivos parciales. Creo que son lo suficientemente específicos y deja claro los distintos milestones que quiero llegar.

2023-05-09 06:38 UTC, JJ requested changes
Perdona por no haber revisado esto antes; recuérdamelo si me retraso, por favor.

2023-05-09 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item{Construir un bot para Telegram que permita obtener la última oferta de cada tienda para el título por el que se le pregunte.}
Los objetivos están siempre en el dominio del problema. La solución concreta (construir un bot de telegram) la tiene que ir dando la metodología de trabajo; no puedes poner la solución antes de ver qué es lo que quiere el usuario. Por ejemplo, ¿por qué no un bot de discord y no de Telegram (no sé si hay)? ¿Por qué no un backend al que se puedan conectar bots de todo tipo?

2023-05-09 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item{Construir un bot para Discord que ofrezca el mismo servicio.}
Lo mismo de arriba. ¿Construir los dos? ¿Sólo uno? ¿Hay alguna solución que pueda ser usada por los dos y además por una web?

2023-05-09 17:44 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +    \item{Construir un bot para Telegram que permita obtener la última oferta de cada tienda para el título por el que se le pregunte.}
Sigo con la conversación por aquí ya que en el comentario de abajo y en este estamos apuntando a lo mismo.

Justamente durante estas semanas que he estado investigando ha ocurrido justamente eso. He "añadido" un objetivo parcial que hace que la entrega cambie. Añadiré LA solución antes de los objetivos parciales para que quede más claro.

2023-05-10 07:24 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +    \item{Construir un bot para Telegram que permita obtener la última oferta de cada tienda para el título por el que se le pregunte.}
En todo caso, recuerda que los productos van a los milestones, no a los objetivos. Los objetivos son siempre en el dominio del problema.

2023-06-16 08:26 UTC, JJ approved these changes
Salvo pequeñas cuestiones de detalle (puedes resolverlas antes de fusionar o después), :+1:

2023-06-16 08:26 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Desde hace ya más de 20 años, el videojuego ha llegado a ser uno de los fenómenos
Y más de 40...

2023-06-16 08:26 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Es por ello que todos recurrimos a buscar ofertas en las distintas tiendas. A lo
Hablando con mi hija y con más gente que sabe del tema, me da la impresión de que con la creación de plataformas de descargas de juegos, la guerra de precios va a desaparecer, quitando así el principal motivo de este trabajo, al menos así escrito. Cabe la posibilidad de que alguien de #2 esté en las mismas circunstancias y conozca bien el mercado, así que veo dos opciones aquí
1. Explicar si esta es una situación que se va a extender en el tiempo, sobre todo con lo que parece que va a ser el fin de las ventas físicas, o si en plataformas de venta puede suceder lo mismo. Si es posible, apoyado por artículos publicados en la web.
2. Plantear el problema de una forma más general: extraer información de ofertas de canales online sobre productos de todo tipo. Evidentemente hay algo específico en los videojuegos en cuanto a como aparecen descritos, pero puede haber posibles extensiones a otros productos, que se pueden abordar haciendo el diseño del producto más genérico o bien en "trabajo futuro" (incluyendo un milestone que no se vaya a hacer en este proyecto)

2023-06-16 08:26 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +algunos especializándose en una plataforma en concreto, y puede que sea complicado
Quizás aclarar que se trata de una plataforma de juegos, no una plataforma de distribución de juegos, ¿no?

2023-06-16 08:26 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +plataformas. Podemos hablar de distintos portales web que nos permiten encontrar
Quizás deberías ser más específico en el lenguaje. Plataformas son plataformas de juegos, o plataformas de distribución como steam, o en este caso que pareces referirte a sistemas de mensajería como Discord. Trata de usar un solo término para cada uno.

2023-06-16 08:26 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +los canales de comunicación anteriormente mencionados}, principalmente en Telegram.
Si este tipo de cosas están en declive (como te he dicho arriba), o tienen un marco temporal pequeño, mencionar aquí también si se podría aplicar a otro tipo de productos.

2023-06-19 17:04 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +Desde hace ya más de 20 años, el videojuego ha llegado a ser uno de los fenómenos
Lo pongo, que creo que me quedé corto con el tiempo 😅

2023-06-19 17:07 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +Es por ello que todos recurrimos a buscar ofertas en las distintas tiendas. A lo
Normalmente los canales de videojuegos que conozco también notifican de ofertas que uno puede encontrar en plataformas de descarga digital de juegos, así que puedo incorporar que también los portales de venta de juegos digitales se tendrán en cuenta

2023-06-19 17:08 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Es por ello que todos recurrimos a buscar ofertas en las distintas tiendas. A lo
OK, si las plataformas también tienen ofertas y se difunden de la misma forma, tenlo en cuenta. Yo pensaba que las plataformas centralizaban los precios y por tanto no había lugares donde se vendieran a menor precio.

2023-06-19 17:09 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +algunos especializándose en una plataforma en concreto, y puede que sea complicado
Creo que debo de utilizar otro término. Creo que debería ser "portal" ya que es una página web donde hacen este tipo de ofertas más generales y que pasa el mismo problema que ocurre con los canales de comunicación.

2023-06-19 17:11 UTC, jero-dev commented on doc/secciones/01_introduccion.tex
> +los canales de comunicación anteriormente mencionados}, principalmente en Telegram.
Diría que poco a poco se irá integrando lo "only-digital", pero creo que la compra física sigue siendo aún importante durante unos cuantos años más.

2023-06-19 17:57 UTC, merged