Creación del esqueleto de la API
jero-dev/proyecto-tfg pull request #15
Opened 2023-05-08 18:53 UTC by jero-dev

En esta solicitud de cambios se incluye el esqueleto para la API que contendrá la lógica de la obtención de los precios de los videojuegos.

En cuanto se fusione esta solicitud de cambios, se cerrarán las peticiones:

- Closes #7

Y se añadirá más valor a las peticiones:

- #9

2023-05-09 06:32 UTC, JJ requested changes
No entiendo muy bien qué tiene que ver esto con la historia de usuario a la que apuntas; parece más bien un setup de un IDE. Tampoco entiendo por qué se empieza a configurar el API antes de todas las etapas anteriores, desde la modelización de alguna parte del problema a la lógica de negocio que vas a usar.
Sería conveniente que procedieras de una forma más sistemática, definiendo más claramente los milestones (productos mínimamente viables), el primero de los cuales va a ser siempre la infraestructura de integración continua.

2023-05-09 06:32 UTC, JJ commented on src/api/PriceScrapperAPI.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
¿Seguro que este fichero tiene que estar en el repo? ¿Se necesita para compilar o algo o es solo configuración del IDE?

2023-05-09 06:32 UTC, JJ commented on src/api/PriceScrapperAPI/PriceScrapperAPI.csproj
> +        <TargetFramework>net7.0</TargetFramework>
Aparte de lo que digo arriba, me da la impresión de que hay una serie de decisiones, incluyendo la elección del lenguaje, que deberías justificar; por ejemplo, al elección de la versión aquí.

2023-05-09 06:32 UTC, JJ commented on src/api/PriceScrapperAPI/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:11889",
Esto no lo acabo de entender.

2023-05-09 18:04 UTC, jero-dev commented
Hola @JJ! Vale, seré más metódico entonces y mantendré mejor las issues y los milestones antes de desarrollar. Aparte, ¿crees que entonces es mejor empezar a desarrollar después de redactar en la memoria el estudio del arte aunque ya se haya hecho la investigación necesaria para esa sección?

Aunque esto se quede en pausa (lo dejaré en borrador hasta que lo confirmes), quiero explicarte un poco acerca de este desarrollo. En este caso estoy utilizando .NET Core (en este caso la versión 7) y es por eso que tiene todo este tipo de dependencias y demás.

Un proyecto de .NET Core se compone siempre de:
- Un fichero Solución (`src/api/PriceScrapperAPI.sln`)
- Mínimo un fichero Proyecto (`src/api/PriceScrapperAPI/PriceScrapperAPI.csproj`)
- Y los ficheros fuente (como por ejemplo, `src/api/PriceScrapperAPI/Program.cs`)

Aparte, para los proyectos centrados en desarrollo web backend se tienen ficheros de configuración (como `launchSettings.json`) que funcionan como los ficheros `.env` para que los desarrolladores que quieren participar en un proyecto lo tengan todo listo para programar.

2023-05-10 07:27 UTC, JJ commented
> Hola @JJ! Vale, seré más metódico entonces y mantendré mejor las issues y los milestones antes de desarrollar. Aparte, ¿crees que entonces es mejor empezar a desarrollar después de redactar en la memoria el estudio del arte aunque ya se haya hecho la investigación necesaria para esa sección?

Si por "desarrollar" quieres decir "hacer un análisis del problema mediante domain driven design", sí.
> 
> Aunque esto se quede en pausa (lo dejaré en borrador hasta que lo confirmes), quiero explicarte un poco acerca de este desarrollo. En este caso estoy utilizando .NET Core (en este caso la versión 7) y es por eso que tiene todo este tipo de dependencias y demás.
> 
> Un proyecto de .NET Core se compone siempre de:
> 
>     * Un fichero Solución (`src/api/PriceScrapperAPI.sln`)
> 
>     * Mínimo un fichero Proyecto (`src/api/PriceScrapperAPI/PriceScrapperAPI.csproj`)
> 
>     * Y los ficheros fuente (como por ejemplo, `src/api/PriceScrapperAPI/Program.cs`)

En general, en los repositorios tiene que haber lo necesario para poder reproducir los resultados usando integración continua. Si los dos ficheros proyecto y solución hacen falta, vale. Si no, pues no.
> 
> 
> Aparte, para los proyectos centrados en desarrollo web backend se tienen ficheros de configuración (como `launchSettings.json`) que funcionan como los ficheros `.env` para que los desarrolladores que quieren participar en un proyecto lo tengan todo listo para programar.

En este caso, el problema es que es demasiado pronto para incluirlos.

Recuerda que también tienes que justificar todas las decisiones, incluyendo la elección del lenguaje de programación.

2023-07-05 20:15 UTC, jero-dev commented
Finalmente, como se ha dicho en la parte del estado del arte, hemos pasado a Go como lenguaje para hacer el proyecto.

Así que han cambiado varios ficheros dentro del directorio `src`.

2023-07-06 05:52 UTC, JJ requested changes
Por favor, pide revisión cuando tengas algo definitivo. Aquí no tienes más que un fichero de ejemplo, y en esta fase ni siquiera es necesario un main.
Ten en cuenta que el desarrollo tiene una serie de fases, y no puedes saltar de la explicación del estado del arte al API. Tienes que hacer un diseño de estructuras de datos y demás. Ni siquiera tengo claro por qué hay un API y por qué hace falta, y no una aplicación monolítica o un bot de Telegram.

2023-11-05 11:23 UTC, closed without merging