Redactar análisis del problema
jero-dev/proyecto-tfg pull request #24
Opened 2023-07-29 10:44 UTC by jero-dev

Esta petición de cambios añade el análisis del problema. En este caso, qué requisitos tiene el problema con sus soluciones y la solución propuesta.

Esta petición cerraría las siguientes tareas:

- No hay aún una tarea creada

2023-09-01 10:56 UTC, JJ reviewed
Varias cosas
1. En el mismo PR que haces el análisis deberías incluir el código; porque si no es imposible si has trasladado correctamente los conceptos del dominio del problema al mismo.
2. Deberías incidir un poco más en el concepto de producto, que va a ser fundamental a la hora de mapear un texto o cadena a productos específicos que pueden estar descritos de formas diferentes.
3. Si vas a crear usuarios diferentes, deberías definir bien las historias de usuario y referirte a ellas desde el texto de la memoria

2023-09-01 10:56 UTC, JJ commented on doc/secciones/04_analisis.tex
> +        \item \textbf{Estudiante:} Usuario que no tiene un gran presupuesto para
Esto serían más historias de usuario que análisis del problema. ¿Has hecho ya las historias de usuario? Si es así, deberías enlazarlos.
En general, el análisis del dominio del problema debería resultar en una serie de estructuras de datos; si los usuarios diferentes sólo van a ser diferentes orígenes de requisitos, no estructuras diferentes, no creo que haga falta modelizarlos aquí.

2023-10-20 08:47 UTC, JJ requested changes
Quizás podrías considerar el análisis del problema parte de los primeros capítulos de implementación, o del capítulo único de implementación.

2023-11-05 10:59 UTC, jero-dev commented on doc/secciones/04_analisis.tex
> +        \item \textbf{Estudiante:} Usuario que no tiene un gran presupuesto para
Con el cambio realizado en una PR anterior, tenemos los usuarios en la introducción. En una de las secciones del capítulo de implementación hemos definido las historias de usuario.

2023-11-06 08:03 UTC, JJ approved these changes
OMFG. No creo que sea capaz de revisar todo esto. Son 21 ficheros, y prácticamente está todo, no sólo el análisis del problema. Entiendo que hay un poco de prisa por terminar, pero por lo mismo tampoco merece la pena que se haga un análisis detallado.

2023-11-06 17:08 UTC, merged