Agregar usuarios e historias de usuario a la memoria
jero-dev/proyecto-tfg pull request #28
Opened 2023-10-17 19:19 UTC by jero-dev

Esta petición de cambios añade los usuarios identificados y las respectivas historias de usuario. Estas últimas se pueden llegar a encontrar también en la sección de issues de GitHub como las issues #2 y #9.

Esta petición cerraría las siguientes tareas:

- Closes #8

2023-10-20 08:34 UTC, JJ requested changes
¿Has considerado la posibilidad de colocar las historias de usuario en otro capítulo? Puede ser la intro o la implementación, cualquier cosa que elijas será correcta, aunque luego tendrás que tener en cuenta las consecuencias

2023-10-25 05:51 UTC, JJ requested changes
Salvo por el usuario indicado, y quizás que expliques qué metodología has seguido (la de "personas" u otra), la nueva ubicación la veo correcta.

2023-10-25 05:51 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\subsection{Tribunal del proyecto de fin de grado}
Este es nuestro usuario *secreto*. No forma parte del proyecto del TFG, sino del TFG en sí.

2023-10-26 09:45 UTC, JJ approved these changes
:+1:  Los comentarios puedes trabajarlos antes de fusionar o crear issues, como prefieras.

2023-10-26 09:45 UTC, JJ commented on README.md
> +### Compilación
No tengo muy claro por qué haces esto, pero no está en el ámbito de este PR.

2023-10-26 09:45 UTC, JJ commented on doc/secciones/03_planificacion.tex
> +Para el seguimiento del desarrollo del proyecto, hemos decidido usar Git como
Git no suele llevar mayúsculas. Usa `{\tt }` para nombres de comandos o alguna otra nomenclatura que lo aclare.

2023-10-26 16:49 UTC, jero-dev commented on doc/secciones/03_planificacion.tex
> +Para el seguimiento del desarrollo del proyecto, hemos decidido usar Git como
Lo tendré en cuenta. Lo añadiré en una próxima issue.

2023-10-26 16:50 UTC, jero-dev commented on README.md
> +### Compilación
Encontré este problema de formato y lo arreglé directamente en esta PR. Aún así, como bien dices, creo que debería de dejarlo fuera de esta PR y ponerlo en una issue para el futuro.

2023-10-26 16:57 UTC, merged